pic-sure-resources/pic-sure-ga4gh-dos/src/main/java/edu/harvard/hms/dbmi/avillach/GA4GHResourceRS.java
pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/service/IResourceRS.java
pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/exception/mapper/NotSupportedExceptionMapper.java

Please take a look at it, this branch is set up in copdgene, you can play with it

picsure 188 modify ga4gh RS to use the target url not from environment, and other improvements

---

pic-sure-api-wildfly/src/test/java/edu/harvard/dbmi/avillach/BaseIT.java
pic-sure-resources/pic-sure-ga4gh-dos/src/main/java/edu/harvard/hms/dbmi/avillach/GA4GHResourceRS.java
pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/HttpClientUtil.java

successfully run mvn clean install for these changes

Apache http client util improvement

---

pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/security/JWTFilter.java

The code is totally the same as a working piece in IRCT

update jwtfilter callTokenIntrospection method to be along with the latest working copy in IRCT

---

pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/security/JWTFilter.java
pic-sure-api-war/src/main/resources/wildfly-configuration/standalone.xml

Update tokenintrospection method so it's returns a user from psama response without going to DB.

Master picsure 245

---

pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/JAXRSConfiguration.java
pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/security/JWTFilter.java
pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/service/PicsureInfoService.java
pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/service/PicsureQueryService.java
pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/service/PicsureSearchService.java
pic-sure-api-war/src/test/java/edu/harvard/dbmi/avillach/PicsureInfoServiceTest.java
pic-sure-api-war/src/test/java/edu/harvard/dbmi/avillach/PicsureQueryServiceTest.java
pic-sure-api-war/src/test/java/edu/harvard/dbmi/avillach/PicsureSearchServiceTest.java
pic-sure-api-wildfly/pom.xml
pic-sure-api-wildfly/src/main/java/edu/harvard/dbmi/avillach/ResourceTestInitializer.java
pic-sure-api-wildfly/src/test/java/edu/harvard/dbmi/avillach/AggregateResourceIT.java
pic-sure-api-wildfly/src/test/java/edu/harvard/dbmi/avillach/HSAPIResourceIT.java
pic-sure-api-wildfly/src/test/java/edu/harvard/dbmi/avillach/IRCTResourceIT.java
pic-sure-resources/pic-sure-ga4gh-dos/src/main/java/edu/harvard/hms/dbmi/avillach/GA4GHResourceRS.java
pic-sure-resources/pic-sure-hsapi-resource/src/main/java/edu/harvard/hms/dbmi/avillach/HSAPIResourceRS.java
pic-sure-resources/pic-sure-irct-resource/src/main/java/edu/harvard/hms/dbmi/avillach/IRCTResourceRS.java
pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/domain/QueryRequest.java
pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/service/ResourceWebClient.java
pic-sure-resources/pic-sure-resource-api/src/test/java/edu/harvard/dbmi/avillach/service/ResourceWebClientTest.java

removed all targetURL restriction, leave targetURL responsibility down to RS level, fixed all related test cases

picsure 242 cleaned all targetURL and fixed the related test cases

---

pic-sure-api-war/pom.xml
pic-sure-api-wildfly/pom.xml
pic-sure-api-wildfly/src/main/resources/wildflyConfiguration/standalone.xml
pom.xml

java 11 support by adding and removing stuff in pom files, and fixed wildfly-maven-plugin

---

pic-sure-resources/pic-sure-irct-resource/pom.xml
pic-sure-resources/pic-sure-irct-resource/src/main/java/edu/harvard/hms/dbmi/avillach/IRCTResourceRS.java
pic-sure-resources/pic-sure-irct-resource/src/main/java/edu/harvard/hms/dbmi/avillach/JAXRSConfiguration.java
pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/HttpClientUtil.java

it's being used in prod environment for couple of months, but it needs an improvement later, there is ticket for the improvement PICSURE 360, please see the JIRA tickets for more details

Picsure 310 guava cache in picsure irct resource service

---

README.md
pic-sure-api-wildfly/pom.xml
pic-sure-api-wildfly/src/main/resources/wildflyConfiguration/standalone.xml

wildfly version to 17 in pic-sure-api-wildfly integration sub module

Picsure 340

---

pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/PicsureRS.java
pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/service/PicsureInfoService.java
pic-sure-api-war/src/test/java/edu/harvard/dbmi/avillach/PicsureInfoServiceTest.java

https://hms-dbmi.atlassian.net/browse/ALS-2047

ALS-2047: Change API resource listing to return a map of UUID:Name

---

pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/HttpClientUtil.java

- I need to be able to set the request timeout
- Configuring requests should probably be done by consumers of this api, hence passing a config and not a timeout

Add RequestConfig to HttpClientUtil

---

pic-sure-api-war/pom.xml
pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/PicsureRS.java
pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/security/JWTFilter.java
pic-sure-api-war/src/main/resources/wildfly-configuration/standalone.xml
pic-sure-api-war/src/test/java/edu/harvard/dbmi/avillach/security/JWTFilterTest.java
pic-sure-resources/pic-sure-resource-api/pom.xml
pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/domain/QueryFormat.java
pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/domain/QueryRequest.java
pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/domain/QueryStatus.java
pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/domain/ResourceInfo.java
pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/domain/SearchResults.java
pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/service/IResourceRS.java
pom.xml

Migrated Swagger Implementation to NHanes

Als 4496 update swagger in gitbook to use nhanes

---

pic-sure-api-data/pom.xml
pic-sure-api-war/pom.xml
pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/PicsureRS.java
pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/service/PicsureSearchService.java
pic-sure-resources/pic-sure-aggregate-data-sharing-resource/pom.xml
pic-sure-resources/pic-sure-ga4gh-dos/pom.xml
pic-sure-resources/pic-sure-hsapi-resource/pom.xml
pic-sure-resources/pic-sure-passthrough-resource/pom.xml
pic-sure-resources/pic-sure-resource-api/pom.xml
pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/domain/PaginatedSearchResult.java
pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/service/IResourceRS.java
pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/service/ResourceWebClient.java
pic-sure-resources/pom.xml
pic-sure-util/pom.xml
pom.xml

Fairly straightforward pass through to HPDS

ALS-4465: Add endpoint to support auto completer for genes

---

pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/main/java/edu/harvard/hms/dbmi/avillach/AggregateDataSharingResourceRS.java
pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/test/java/edu/harvard/hms/dbmi/avillach/AggregateDataSharingResourceRSAcceptanceTests.java
pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/test/java/edu/harvard/hms/dbmi/avillach/ProxyPostEndpointMocker.java
pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/HttpClientUtil.java

- Make logging more consistent
- Check for 2xx response codes, not just 200
- Deduplicate constructor code
- Make some constants final
- Fix 2xx predicates
- Added coverage to AggregateDataSharingResourceRS
- Made a helper class for those tests
- Fixed a marshalling bug

 [ALS-4412] - Implement query ID API endpoints (#111)

---

pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/domain/PaginatedSearchResult.java
pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/service/ResourceWebClient.java
pic-sure-resources/pic-sure-resource-api/src/test/java/edu/harvard/dbmi/avillach/domain/PaginatedSearchResultTest.java

Nothing major here, a couple changes here from the last PR did not get properly tested and were breaking (ex: removing lombok).

ALS-4777: Fix issues with genomic autocomplete endpoint

---

pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/main/java/edu/harvard/hms/dbmi/avillach/AggregateDataSharingResourceRS.java
pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/DataProcessingService.java

[ALS-4956] : Always obfuscate open pic-sure visualizations

---

pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/main/java/edu/harvard/hms/dbmi/avillach/AggregateDataSharingResourceRS.java

- Add more result types to agg data sharing rs

 [ALS-4906] Add Variant Explorer in GIC Common Area

---

pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/main/java/edu/harvard/hms/dbmi/avillach/AggregateDataSharingResourceRS.java
pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/DataProcessingService.java
pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/VisualizationUtil.java

[ALS-4467] We now pre-process the categorical variables. By doing this we can ensure that the other category is obfuscated with the correct total.

[ALS-4467] other study bar on var dist fix

---

pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/main/java/edu/harvard/hms/dbmi/avillach/AggregateDataSharingResourceRS.java
pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/test/java/edu/harvard/hms/dbmi/avillach/AggregateDataSharingResourceRSAcceptanceTests.java
pic-sure-resources/pic-sure-ga4gh-dos/src/main/java/edu/harvard/hms/dbmi/avillach/GA4GHResourceRS.java
pic-sure-resources/pic-sure-hsapi-resource/src/main/java/edu/harvard/hms/dbmi/avillach/HSAPIResourceRS.java
pic-sure-resources/pic-sure-passthrough-resource/src/test/java/edu/harvard/hms/dbmi/avillach/resource/passthru/PassThroughResourceRSTest.java
pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/service/IResourceRS.java
pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/VisualizationService.java
pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/HttpClientUtil.java
pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/converter/UUIDParamConverter.java
pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/converter/UUIDParamConverterProvider.java

[ALS-4980] Resolve medium severity Checkmarx security findings.

[ALS-4980] pic sure medium findings

---

pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/main/java/edu/harvard/hms/dbmi/avillach/AggregateDataSharingResourceRS.java
pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/main/java/edu/harvard/hms/dbmi/avillach/service/HeaderFilter.java
pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/main/java/edu/harvard/hms/dbmi/avillach/service/RequestScopedHeader.java
pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/ApplicationProperties.java
pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/VisualizationResource.java
pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/DataProcessingService.java
pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/HpdsService.java
pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/VisualizationService.java
pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/Utilities.java
pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/VisualizationUtil.java

[ALS-4957] BDC StatViz: Continuous bar should show true number when participants have only one value.
[ALS-5228] BDC Open StatViz was always obfuscated. It is now obfuscated as needed.
[ALS-5197] Fix "Other" bar not displaying in Authorized PIC-SURE

Stat vis fixes and enhancements

---

pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/PicsureRS.java
pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/service/IResourceRS.java
pic-sure-resources/pic-sure-resource-api/src/main/java/edu/harvard/dbmi/avillach/service/ProxyWebClient.java
pic-sure-resources/pic-sure-resource-api/src/test/java/edu/harvard/dbmi/avillach/service/ProxyWebClientTest.java
pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/HttpClientUtil.java

- Create endpoint to proxy requests

[ALS-5065] Create proxy endpoint to enable dockerized services

---

pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/DataProcessingService.java

[ALS-5356] _harmonized_consent displayed in Open Variable Distributions

[ALS-5356] _harmonized_consent displayed in Open Variable Distributions

---

pic-sure-resources/pic-sure-visualization-resource/src/main/resources/META-INF/persistence.xml

Syncing the release branch with master after a hotfix

Syncing the release branch with master after a hotfix

---

pic-sure-resources/pic-sure-aggregate-data-sharing-resource/src/main/java/edu/harvard/hms/dbmi/avillach/AggregateDataSharingResourceRS.java

- Very confused as to how this was working before

[ALS-0000] Fix aggregate resource

---

README.md
code-formatting/eclipse-formatter.xml
code-formatting/pre-commit.sh
pom.xml

- Add formatting config
- Add pre commit hook to format things
- Add formatting stuff to pom
- Add directions to README

[ALS-5482] - PIC-SURE Code formatting

---

pic-sure-api-data/src/main/java/edu/harvard/dbmi/avillach/data/entity/Resource.java
pic-sure-api-data/src/main/java/edu/harvard/dbmi/avillach/data/repository/QueryRepository.java
pic-sure-api-data/src/main/java/edu/harvard/dbmi/avillach/data/repository/ResourceRepository.java
pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/service/PicsureInfoService.java
pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/service/PicsureQueryService.java
pic-sure-resources/pic-sure-visualization-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/DataProcessingService.java
pic-sure-resources/pic-sure-visualization-resource/src/test/java/edu/harvard/hms/dbmi/avillach/resource/visualization/service/VisualizationUtilTests.java
pic-sure-util/src/main/java/edu/harvard/dbmi/avillach/util/VisualizationUtil.java

 Merging for 03-28 release

---

pic-sure-api-war/src/main/java/edu/harvard/dbmi/avillach/PicsureRS.java

application/json makes jQuery try to automatically parse it

ALS-6511: Set async query result to application/octet content type
